package verify

import (
	"context"
	"testing"

	"github.com/0x1Adi/Klarion/internal/finding"
)

func TestHeuristicClassify(t *testing.T) {
	h := newHeuristic()

	tests := []struct {
		name string
		req  Request
		want finding.VerdictStatus
	}{
		{
			name: "specific rule with known prefix -> secret",
			req:  Request{RuleID: "aws-access-key-id", Secret: "AKIAIOSFODNN7EXAMPLEX", Entropy: 0.6},
			// "EXAMPLE" marker present -> false positive wins over rule.
			want: finding.VerdictFalsePositive,
		},
		{
			name: "specific rule with known prefix, no marker -> secret",
			req:  Request{RuleID: "github-pat", Secret: "ghp_abcdefghijklmnopqrstuvwxyz0123456789", Entropy: 0.9},
			want: finding.VerdictSecret,
		},
		{
			name: "specific rule high entropy -> secret",
			req:  Request{RuleID: "stripe-secret", Secret: "R8fZq2WmVx7Lp0Ktn3Yb", Entropy: 0.95},
			want: finding.VerdictSecret,
		},
		{
			name: "specific rule low entropy -> still secret (trust rule)",
			req:  Request{RuleID: "private-key", Secret: "someModeratelyRandom99", Entropy: 0.4},
			want: finding.VerdictSecret,
		},
		{
			name: "placeholder marker in value -> false positive",
			req:  Request{RuleID: "generic-high-entropy", Secret: "your_api_key_here", Entropy: 0.5},
			want: finding.VerdictFalsePositive,
		},
		{
			name: "changeme placeholder -> false positive",
			req:  Request{RuleID: "generic-high-entropy", Secret: "changeme123456789ABC", Entropy: 0.9},
			want: finding.VerdictFalsePositive,
		},
		{
			name: "uuid -> false positive",
			req:  Request{RuleID: "generic-high-entropy", Secret: "550e8400-e29b-41d4-a716-446655440000", Entropy: 0.8},
			want: finding.VerdictFalsePositive,
		},
		{
			name: "git sha (40 hex) generic -> false positive",
			req:  Request{RuleID: "generic-high-entropy", Secret: "da39a3ee5e6b4b0d3255bfef95601890afd80709", Entropy: 0.7},
			want: finding.VerdictFalsePositive,
		},
		{
			name: "generic high entropy in test path -> false positive",
			req:  Request{RuleID: "generic-high-entropy", Secret: "Zk9Qp2Vx7Lm4Rn8Ty1Wc", Entropy: 0.95, FilePath: "internal/foo_test.go"},
			want: finding.VerdictFalsePositive,
		},
		{
			name: "generic high entropy called a fixture in context -> false positive",
			req:  Request{RuleID: "generic-high-entropy", Secret: "Zk9Qp2Vx7Lm4Rn8Ty1Wc", Entropy: 0.95, Context: "// fixture value, regenerated by make testdata"},
			want: finding.VerdictFalsePositive,
		},
		// The context window is only a few lines wide, so a weak marker near a
		// candidate is not evidence about the candidate. Each of these used to
		// discard the finding outright.
		{
			name: "generic high entropy under a path containing 'latest' -> uncertain",
			req:  Request{RuleID: "generic-high-entropy", Secret: "Zk9Qp2Vx7Lm4Rn8Ty1Wc", Entropy: 0.95, FilePath: "api/latest/config.go"},
			want: finding.VerdictUncertain,
		},
		{
			name: "generic high entropy next to the word spec -> uncertain",
			req:  Request{RuleID: "generic-high-entropy", Secret: "Zk9Qp2Vx7Lm4Rn8Ty1Wc", Entropy: 0.95, FilePath: "internal/server/config.go", Context: "// see the spec for details"},
			want: finding.VerdictUncertain,
		},
		{
			name: "generic high entropy next to an example.com URL -> uncertain",
			req:  Request{RuleID: "generic-high-entropy", Secret: "Zk9Qp2Vx7Lm4Rn8Ty1Wc", Entropy: 0.95, FilePath: "internal/server/config.go", Context: `endpoint := "https://api.example.com/v1"`},
			want: finding.VerdictUncertain,
		},
		{
			name: "generic high entropy in a manifest file -> uncertain",
			req:  Request{RuleID: "generic-high-entropy", Secret: "Zk9Qp2Vx7Lm4Rn8Ty1Wc", Entropy: 0.95, FilePath: "build/manifest.json"},
			want: finding.VerdictUncertain,
		},
		{
			name: "generic high entropy in a spec directory -> false positive",
			req:  Request{RuleID: "generic-high-entropy", Secret: "Zk9Qp2Vx7Lm4Rn8Ty1Wc", Entropy: 0.95, FilePath: "spec/models/user_spec.rb"},
			want: finding.VerdictFalsePositive,
		},
		{
			name: "generic high entropy in a dotted spec file -> false positive",
			req:  Request{RuleID: "generic-high-entropy", Secret: "Zk9Qp2Vx7Lm4Rn8Ty1Wc", Entropy: 0.95, FilePath: "src/api.spec.ts"},
			want: finding.VerdictFalsePositive,
		},
		{
			name: "generic high entropy prod path -> uncertain",
			req:  Request{RuleID: "generic-high-entropy", Secret: "Zk9Qp2Vx7Lm4Rn8Ty1Wc", Entropy: 0.95, FilePath: "internal/server/config.go"},
			want: finding.VerdictUncertain,
		},
		{
			name: "generic low entropy prod path -> uncertain",
			req:  Request{RuleID: "generic-high-entropy", Secret: "mildlyRandomValue22", Entropy: 0.5, FilePath: "cmd/main.go"},
			want: finding.VerdictUncertain,
		},
		{
			name: "empty secret -> uncertain",
			req:  Request{RuleID: "generic-high-entropy", Secret: ""},
			want: finding.VerdictUncertain,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := h.classify(tt.req)
			if got.Status != tt.want {
				t.Errorf("classify(%q) status = %q, want %q (reason: %s)", tt.req.Secret, got.Status, tt.want, got.Reason)
			}
			if got.Verifier != "heuristic" {
				t.Errorf("verifier = %q, want heuristic", got.Verifier)
			}
			if got.Confidence < 0 || got.Confidence > 1 {
				t.Errorf("confidence %v out of range", got.Confidence)
			}
		})
	}
}

func TestHeuristicVerifyOrderAndCount(t *testing.T) {
	h := newHeuristic()
	batch := []Request{
		{RuleID: "generic-high-entropy", Secret: "your_api_key"},
		{RuleID: "github-pat", Secret: "ghp_zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz"},
		{RuleID: "generic-high-entropy", Secret: "Zk9Qp2Vx7Lm4Rn8Ty1Wc", Entropy: 0.95, FilePath: "app/server.go"},
	}
	got, err := h.Verify(context.Background(), batch)
	if err != nil {
		t.Fatalf("Verify error: %v", err)
	}
	if len(got) != len(batch) {
		t.Fatalf("got %d verdicts, want %d", len(got), len(batch))
	}
	want := []finding.VerdictStatus{
		finding.VerdictFalsePositive,
		finding.VerdictSecret,
		finding.VerdictUncertain,
	}
	for i := range want {
		if got[i].Status != want[i] {
			t.Errorf("verdict[%d] = %q, want %q", i, got[i].Status, want[i])
		}
	}
}

func TestHeuristicDeterministic(t *testing.T) {
	h := newHeuristic()
	req := Request{RuleID: "generic-high-entropy", Secret: "Zk9Qp2Vx7Lm4Rn8Ty1Wc", Entropy: 0.95}
	first := h.classify(req)
	for i := 0; i < 50; i++ {
		if got := h.classify(req); got != first {
			t.Fatalf("non-deterministic verdict: %+v != %+v", got, first)
		}
	}
}

func TestHeuristicName(t *testing.T) {
	if got := newHeuristic().Name(); got != "heuristic" {
		t.Errorf("Name() = %q, want heuristic", got)
	}
}
