#!/usr/bin/env sh
# Generates testdata/leaky.env, the demo fixture used to smoke-test the scanner
# end to end (`klarion scan testdata/` should light up).
#
# The fixture is generated rather than committed because it has to contain
# credentials in real issuer formats to be worth anything, and a committed file
# cannot hide those behind a concatenation the way the Go tests do. GitHub push
# protection blocks the push, and every fork inherits the problem. So the parts
# live here split apart and get joined at generation time.
#
# Every value below is synthetic and has never been a live credential.
set -eu

out="$(dirname "$0")/leaky.env"

# Issuer prefixes are kept apart from the bodies so that neither half matches a
# scanner rule on its own. Only the joined output does.
aws_p='AKIA';     aws_b='Z7QEXAMPLE4KUB2Q'
github_p='ghp';   github_b='ab12CD34ef56GH78ij90KL12mn34OP56qr78'
stripe_p='sk';    stripe_b='51H8xkLDVc0J9mZq3rT7wYpN4bXfA2eKd'

cat > "$out" <<EOF
# Fixture with intentionally-fake secrets for smoke testing.
# Generated by testdata/gen-leaky-env.sh — do not commit. See that script for why.
AWS_ACCESS_KEY_ID=${aws_p}${aws_b}
GITHUB_TOKEN=${github_p}_${github_b}
STRIPE_KEY=${stripe_p}_live_${stripe_b}
DATABASE_URL=postgres://admin:S3cr3tP@ssw0rd9x@db.example.com:5432/prod
GREETING=hello_world_this_is_not_secret
EOF

echo "wrote $out"
